name: Advent of Code
on:
  schedule:
  - cron: 0 5 * * *
    
  workflow_dispatch:

jobs:
  
  create_daily_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d')" >> $GITHUB_ENV

      - name: Create Daily Issue
        uses: imjohnbo/issue-bot@v2
        with:
          title: Advent of Code - Day $(date +'%d')
          assignees: "jwbb1508" # GitHub handles without the @
          labels: "enhancement"
          pinned: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
